name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      
env:
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
  
jobs:
  test:
    runs-on: ubuntu-22.04

    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
      
    strategy:
      matrix:
        java-version: [21, 25]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven

      - name: Build and test with Maven
        run: mvn -B verify

      - name: Package application
        run: mvn -B package -DskipTests

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.java-version }}
          path: target/*.jar

      - name: Send failure notification
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"Build failed for ${{ github.repository }} on branch ${{ github.ref }}\"}" \
               $WEBHOOK_URL
